name: Go Web App CI Pipeline
on:
    push:
        branches: 
            - main
        paths-ignore: 
            - 'Readme.md'
            - 'helm-charts/**'
            - 'k8s-manifest/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Set Up Go 1.22.5
              uses: actions/setup-go@v2
              with:
                go-version: 1.22.5

            - name: Build the application
              run: go build -o go-web-app

            - name: Test the application
              run: go test ./...

    code-quality:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Run Golang-ci lint
              uses: golangci/golangci-lint-action@v6
              with:
                version: v1.56.2

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Set up Docker BuildX
              uses: docker/setup-buildx-action@v1

            - name: Login to Docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.run_id }}

    update-newtag-in-helm-charts:
        runs-on: ubuntu-latest
        needs: deploy

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.TOKEN }}

            - name: Update tag in the helm chart
              run: |
                sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm-charts/values.yaml

            - name: Commit and push changes
              run: |
                git config --global user.name "Romu Tiwari"
                git config --global user.email "tromu98@gmail.com"
                git add helm-charts/values.yaml
                git commit -m "Updated tag in Helm Chart"
                git push

